const countryList = [
  { name: 'Afghanistan', code: '+93', icon: '🇦🇫' },
  { name: 'Albania', code: '+355', icon: '🇦🇱' },
  { name: 'Algeria', code: '+213', icon: '🇩🇿' },
  { name: 'AmericanSamoa', code: '+1684', icon: '🇦🇸' },
  { name: 'Andorra', code: '+376', icon: '🇦🇩' },
  { name: 'Angola', code: '+244', icon: '🇦🇴' },
  { name: 'Anguilla', code: '+1264', icon: '🇦🇮' },
  { name: 'Antarctica', code: '+672', icon: '🇦🇶' },
  { name: 'Antigua and Barbuda', code: '+1268', icon: '🇦🇬' },
  { name: 'Argentina', code: '+54', icon: '🇦🇷' },
  { name: 'Armenia', code: '+374', icon: '🇦🇲' },
  { name: 'Aruba', code: '+297', icon: '🇦🇼' },
  { name: 'Australia', code: '+61', icon: '🇦🇺' },
  { name: 'Austria', code: '+43', icon: '🇦🇹' },
  { name: 'Azerbaijan', code: '+994', icon: '🇦🇿' },
  { name: 'Bahamas', code: '+1242', icon: '🇧🇸' },
  { name: 'Bahrain', code: '+973', icon: '🇧🇭' },
  { name: 'Bangladesh', code: '+880', icon: '🇧🇩' },
  { name: 'Barbados', code: '+1246', icon: '🇧🇧' },
  { name: 'Belarus', code: '+375', icon: '🇧🇾' },
  { name: 'Belgium', code: '+32', icon: '🇧🇪' },
  { name: 'Belize', code: '+501', icon: '🇧🇿' },
  { name: 'Benin', code: '+229', icon: '🇧🇯' },
  { name: 'Bermuda', code: '+1441', icon: '🇧🇲' },
  { name: 'Bhutan', code: '+975', icon: '🇧🇹' },
  { name: 'Bolivia, Plurinational State of', code: '+591', icon: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', code: '+387', icon: '🇧🇦' },
  { name: 'Botswana', code: '+267', icon: '🇧🇼' },
  { name: 'Brazil', code: '+55', icon: '🇧🇷' },
  { name: 'British Indian Ocean Territory', code: '+246', icon: '🇮🇴' },
  { name: 'Brunei Darussalam', code: '+673', icon: '🇧🇳' },
  { name: 'Bulgaria', code: '+359', icon: '🇧🇬' },
  { name: 'Burkina Faso', code: '+226', icon: '🇧🇫' },
  { name: 'Burundi', code: '+257', icon: '🇧🇮' },
  { name: 'Cambodia', code: '+855', icon: '🇰🇭' },
  { name: 'Cameroon', code: '+237', icon: '🇨🇲' },
  { name: 'Canada', code: '+1', icon: '🇨🇦' },
  { name: 'Cape Verde', code: '+238', icon: '🇨🇻' },
  { name: 'Cayman Islands', code: '+345', icon: '🇰🇾' },
  { name: 'Central African Republic', code: '+236', icon: '🇨🇫' },
  { name: 'Chad', code: '+235', icon: '🇹🇩' },
  { name: 'Chile', code: '+56', icon: '🇨🇱' },
  { name: 'China', code: '+86', icon: '🇨🇳' },
  { name: 'Christmas Island', code: '+61', icon: '🇨🇽' },
  { name: 'Cocos (Keeling) Islands', code: '+61', icon: '🇨🇨' },
  { name: 'Colombia', code: '+57', icon: '🇨🇴' },
  { name: 'Comoros', code: '+269', icon: '🇰🇲' },
  { name: 'Congo', code: '+242', icon: '🇨🇬' },
  { name: 'Congo, The Democratic Republic of the', code: '+243', icon: '🇨🇩' },
  { name: 'Cook Islands', code: '+682', icon: '🇨🇰' },
  { name: 'Costa Rica', code: '+506', icon: '🇨🇷' },
  { name: "Cote d'Ivoire", code: '+225', icon: '🇨🇮' },
  { name: 'Croatia', code: '+385', icon: '🇭🇷' },
  { name: 'Cuba', code: '+53', icon: '🇨🇺' },
  { name: 'Cyprus', code: '+357', icon: '🇨🇾' },
  { name: 'Czech Republic', code: '+420', icon: '🇨🇿' },
  { name: 'Denmark', code: '+45', icon: '🇩🇰' },
  { name: 'Djibouti', code: '+253', icon: '🇩🇯' },
  { name: 'Dominica', code: '+1767', icon: '🇩🇲' },
  { name: 'Dominican Republic', code: '+1849', icon: '🇩🇴' },
  { name: 'Ecuador', code: '+593', icon: '🇪🇨' },
  { name: 'Egypt', code: '+20', icon: '🇪🇬' },
  { name: 'El Salvador', code: '+503', icon: '🇸🇻' },
  { name: 'Equatorial Guinea', code: '+240', icon: '🇬🇶' },
  { name: 'Eritrea', code: '+291', icon: '🇪🇷' },
  { name: 'Estonia', code: '+372', icon: '🇪🇪' },
  { name: 'Ethiopia', code: '+251', icon: '🇪🇹' },
  { name: 'Falkland Islands (Malvinas)', code: '+500', icon: '🇫🇰' },
  { name: 'Faroe Islands', code: '+298', icon: '🇫🇴' },
  { name: 'Fiji', code: '+679', icon: '🇫🇯' },
  { name: 'Finland', code: '+358', icon: '🇫🇮' },
  { name: 'France', code: '+33', icon: '🇫🇷' },
  { name: 'French Guiana', code: '+594', icon: '🇬🇫' },
  { name: 'French Polynesia', code: '+689', icon: '🇵🇫' },
  { name: 'Gabon', code: '+241', icon: '🇬🇦' },
  { name: 'Gambia', code: '+220', icon: '🇬🇲' },
  { name: 'Georgia', code: '+995', icon: '🇬🇪' },
  { name: 'Germany', code: '+49', icon: '🇩🇪' },
  { name: 'Ghana', code: '+233', icon: '🇬🇭' },
  { name: 'Gibraltar', code: '+350', icon: '🇬🇮' },
  { name: 'Greece', code: '+30', icon: '🇬🇷' },
  { name: 'Greenland', code: '+299', icon: '🇬🇱' },
  { name: 'Grenada', code: '+1473', icon: '🇬🇩' },
  { name: 'Guadeloupe', code: '+590', icon: '🇬🇵' },
  { name: 'Guam', code: '+1671', icon: '🇬🇺' },
  { name: 'Guatemala', code: '+502', icon: '🇬🇹' },
  { name: 'Guernsey', code: '+44', icon: '🇬🇬' },
  { name: 'Guinea', code: '+224', icon: '🇬🇳' },
  { name: 'Guinea-Bissau', code: '+245', icon: '🇬🇼' },
  { name: 'Guyana', code: '+592', icon: '🇬🇾' },
  { name: 'Haiti', code: '+509', icon: '🇭🇹' },
  { name: 'Holy See (Vatican City State)', code: '+379', icon: '🇻🇦' },
  { name: 'Honduras', code: '+504', icon: '🇭🇳' },
  { name: 'Hong Kong', code: '+852', icon: '🇭🇰' },
  { name: 'Hungary', code: '+36', icon: '🇭🇺' },
  { name: 'Iceland', code: '+354', icon: '🇮🇸' },
  { name: 'India', code: '+91', icon: '🇮🇳' },
  { name: 'Indonesia', code: '+62', icon: '🇮🇩' },
  { name: 'Iran, Islamic Republic of', code: '+98', icon: '🇮🇷' },
  { name: 'Iraq', code: '+964', icon: '🇮🇶' },
  { name: 'Ireland', code: '+353', icon: '🇮🇪' },
  { name: 'Isle of Man', code: '+44', icon: '🇮🇲' },
  { name: 'Israel', code: '+972', icon: '🇮🇱' },
  { name: 'Italy', code: '+39', icon: '🇮🇹' },
  { name: 'Jamaica', code: '+1876', icon: '🇯🇲' },
  { name: 'Japan', code: '+81', icon: '🇯🇵' },
  { name: 'Jersey', code: '+44', icon: '🇯🇪' },
  { name: 'Jordan', code: '+962', icon: '🇯🇴' },
  { name: 'Kazakhstan', code: '+77', icon: '🇰🇿' },
  { name: 'Kenya', code: '+254', icon: '🇰🇪' },
  { name: 'Kiribati', code: '+686', icon: '🇰🇮' },
  { name: "Korea, Democratic People's Republic of", code: '+850', icon: '🇰🇵' },
  { name: 'Korea, Republic of', code: '+82', icon: '🇰🇷' },
  { name: 'Kuwait', code: '+965', icon: '🇰🇼' },
  { name: 'Kyrgyzstan', code: '+996', icon: '🇰🇬' },
  { name: "Lao People's Democratic Republic", code: '+856', icon: '🇱🇦' },
  { name: 'Latvia', code: '+371', icon: '🇱🇻' },
  { name: 'Lebanon', code: '+961', icon: '🇱🇧' },
  { name: 'Lesotho', code: '+266', icon: '🇱🇸' },
  { name: 'Liberia', code: '+231', icon: '🇱🇷' },
  { name: 'Libyan Arab Jamahiriya', code: '+218', icon: '🇱🇾' },
  { name: 'Liechtenstein', code: '+423', icon: '🇱🇮' },
  { name: 'Lithuania', code: '+370', icon: '🇱🇹' },
  { name: 'Luxembourg', code: '+352', icon: '🇱🇺' },
  { name: 'Macao', code: '+853', icon: '🇲🇴' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: '+389', icon: '🇲🇰' },
  { name: 'Madagascar', code: '+261', icon: '🇲🇬' },
  { name: 'Malawi', code: '+265', icon: '🇲🇼' },
  { name: 'Malaysia', code: '+60', icon: '🇲🇾' },
  { name: 'Maldives', code: '+960', icon: '🇲🇻' },
  { name: 'Mali', code: '+223', icon: '🇲🇱' },
  { name: 'Malta', code: '+356', icon: '🇲🇹' },
  { name: 'Marshall Islands', code: '+692', icon: '🇲🇭' },
  { name: 'Martinique', code: '+596', icon: '🇲🇶' },
  { name: 'Mauritania', code: '+222', icon: '🇲🇷' },
  { name: 'Mauritius', code: '+230', icon: '🇲🇺' },
  { name: 'Mayotte', code: '+262', icon: '🇾🇹' },
  { name: 'Mexico', code: '+52', icon: '🇲🇽' },
  { name: 'Micronesia, Federated States of', code: '+691', icon: '🇫🇲' },
  { name: 'Moldova, Republic of', code: '+373', icon: '🇲🇩' },
  { name: 'Monaco', code: '+377', icon: '🇲🇨' },
  { name: 'Mongolia', code: '+976', icon: '🇲🇳' },
  { name: 'Montenegro', code: '+382', icon: '🇲🇪' },
  { name: 'Montserrat', code: '+1664', icon: '🇲🇸' },
  { name: 'Morocco', code: '+212', icon: '🇲🇦' },
  { name: 'Mozambique', code: '+258', icon: '🇲🇿' },
  { name: 'Myanmar', code: '+95', icon: '🇲🇲' },
  { name: 'Namibia', code: '+264', icon: '🇳🇦' },
  { name: 'Nauru', code: '+674', icon: '🇳🇷' },
  { name: 'Nepal', code: '+977', icon: '🇳🇵' },
  { name: 'Netherlands', code: '+31', icon: '🇳🇱' },
  { name: 'Netherlands Antilles', code: '+599', icon: '🇦🇳' },
  { name: 'New Caledonia', code: '+687', icon: '🇳🇨' },
  { name: 'New Zealand', code: '+64', icon: '🇳🇮' },
  { name: 'Niger', code: '+227', icon: '🇳🇪' },
  { name: 'Nigeria', code: '+234', icon: '🇳🇬' },
  { name: 'Niue', code: '+683', icon: '🇳🇺' },
  { name: 'Norfolk Island', code: '+672', icon: '🇳🇫' },
  { name: 'Northern Mariana Islands', code: '+1670', icon: '🇲🇵' },
  { name: 'Norway', code: '+47', icon: '🇳🇴' },
  { name: 'Oman', code: '+968', icon: '🇴🇲' },
  { name: 'Pakistan', code: '+92', icon: '🇵🇰' },
  { name: 'Palau', code: '+680', icon: '🇵🇼' },
  { name: 'Palestinian Territory, Occupied', code: '+970', icon: '🇵🇸' },
  { name: 'Panama', code: '+507', icon: '🇵🇦' },
  { name: 'Papua New Guinea', code: '+675', icon: '🇵🇬' },
  { name: 'Paraguay', code: '+595', icon: '🇵🇾' },
  { name: 'Peru', code: '+51', icon: '🇵🇪' },
  { name: 'Philippines', code: '+63', icon: '🇵🇭' },
  { name: 'Pitcairn', code: '+872', icon: '🇵🇳' },
  { name: 'Poland', code: '+48', icon: '🇵🇱' },
  { name: 'Portugal', code: '+351', icon: '🇵🇹' },
  { name: 'Puerto Rico', code: '+1939', icon: '🇵🇷' },
  { name: 'Qatar', code: '+974', icon: '🇶🇦' },
  { name: 'Romania', code: '+40', icon: '🇷🇴' },
  { name: 'Russia', code: '+7', icon: '🇷🇺' },
  { name: 'Rwanda', code: '+250', icon: '🇷🇼' },
  { name: 'Réunion', code: '+262', icon: '🇷🇪' },
  { name: 'Saint Barthélemy', code: '+590', icon: '🇧🇱' },
  { name: 'Saint Helena, Ascension and Tristan Da Cunha', code: '+290', icon: '🇸🇭' },
  { name: 'Saint Kitts and Nevis', code: '+1869', icon: '🇰🇳' },
  { name: 'Saint Lucia', code: '+1758', icon: '🇱🇨' },
  { name: 'Saint Martin', code: '+590', icon: '🇲🇫' },
  { name: 'Saint Pierre and Miquelon', code: '+508', icon: '🇵🇲' },
  { name: 'Saint Vincent and the Grenadines', code: '+1784', icon: '🇻🇨' },
  { name: 'Samoa', code: '+685', icon: '🇼🇸' },
  { name: 'San Marino', code: '+378', icon: '🇸🇲' },
  { name: 'Sao Tome and Principe', code: '+239', icon: '🇸🇹' },
  { name: 'Saudi Arabia', code: '+966', icon: '🇸🇦' },
  { name: 'Senegal', code: '+221', icon: '🇸🇳' },
  { name: 'Serbia', code: '+381', icon: '🇷🇸' },
  { name: 'Seychelles', code: '+248', icon: '🇸🇨' },
  { name: 'Sierra Leone', code: '+232', icon: '🇸🇱' },
  { name: 'Singapore', code: '+65', icon: '🇸🇬' },
  { name: 'Slovakia', code: '+421', icon: '🇸🇰' },
  { name: 'Slovenia', code: '+386', icon: '🇸🇮' },
  { name: 'Solomon Islands', code: '+677', icon: '🇸🇧' },
  { name: 'Somalia', code: '+252', icon: '🇸🇴' },
  { name: 'South Africa', code: '+27', icon: '🇿🇦' },
  { name: 'South Georgia and the South Sandwich Islands', code: '+500', icon: '🇬🇸' },
  { name: 'Spain', code: '+34', icon: '🇪🇸' },
  { name: 'Sri Lanka', code: '+94', icon: '🇱🇰' },
  { name: 'Sudan', code: '+249', icon: '🇸🇩' },
  { name: 'South Sudan', code: '+211', icon: '🇸🇸' },
  { name: 'Suriname', code: '+597', icon: '🇸🇷' },
  { name: 'Svalbard and Jan Mayen', code: '+47', icon: '🇸🇯' },
  { name: 'Swaziland', code: '+268', icon: '🇸🇿' },
  { name: 'Sweden', code: '+46', icon: '🇸🇪' },
  { name: 'Switzerland', code: '+41', icon: '🇨🇭' },
  { name: 'Syrian Arab Republic', code: '+963', icon: '🇸🇾' },
  { name: 'Taiwan, Province of China', code: '+886', icon: '🇹🇼' },
  { name: 'Tajikistan', code: '+992', icon: '🇹🇯' },
  { name: 'Tanzania, United Republic of', code: '+255', icon: '🇹🇿' },
  { name: 'Thailand', code: '+66', icon: '🇹🇭' },
  { name: 'Timor-Leste', code: '+670', icon: '🇹🇱' },
  { name: 'Togo', code: '+228', icon: '🇹🇬' },
  { name: 'Tokelau', code: '+690', lag: '🇹🇰' },
  { name: 'Tonga', code: '+676', icon: '🇹🇴' },
  { name: 'Trinidad and Tobago', code: '+1868', icon: '🇹🇹' },
  { name: 'Tunisia', code: '+216', icon: '🇹🇳' },
  { name: 'Turkey', code: '+90', icon: '🇹🇷' },
  { name: 'Turkmenistan', code: '+993', icon: '🇹🇲' },
  { name: 'Turks and Caicos Islands', code: '+1649', icon: '🇹🇨' },
  { name: 'Tuvalu', code: '+688', icon: '🇹🇻' },
  { name: 'Uganda', code: '+256', icon: '🇺🇬' },
  { name: 'Ukraine', code: '+380', icon: '🇺🇦' },
  { name: 'United Arab Emirates', code: '+971', icon: '🇦🇪' },
  { name: 'United Kingdom', code: '+44', icon: '🇬🇧' },
  { name: 'United States', code: '+1', icon: '🇺🇸' },
  { name: 'Uruguay', code: '+598', icon: '🇺🇾' },
  { name: 'Uzbekistan', code: '+998', icon: '🇺🇿' },
  { name: 'Vanuatu', code: '+678', icon: '🇻🇺' },
  { name: 'Venezuela, Bolivarian Republic of', code: '+58', icon: '🇻🇪' },
  { name: 'Viet Nam', code: '+84', icon: '🇻🇳' },
  { name: 'Virgin Islands, British', code: '+1284', icon: '🇻🇬' },
  { name: 'Virgin Islands, U.S.', code: '+1340', icon: '🇻🇮' },
  { name: 'Wallis and Futuna', code: '+681', icon: '🇼🇫' },
  { name: 'Yemen', code: '+967', icon: '🇾🇪' },
  { name: 'Zambia', code: '+260', icon: '🇿🇲' },
  { name: 'Zimbabwe', code: '+263', icon: '🇿🇼' },
  { name: 'Åland Islands', code: '+358', icon: '🇦🇽' },
]

export default countryList
