export const DAY_IN_MS = 24 * 60 * 60 * 1000
export const DATE_FORMAT = 'DD MMM YY'
export const WITH_TIME = DATE_FORMAT + ' h:mm A'
export const complete = 'COMPLETE'
export const addItemsQuestionCode = 'QUE_ADD_ITEMS_GRP'
export const quickAddItemsQuestionCode = 'QUE_QUICK_ADD_ITEMS_GRP'
export const dashboardViewQuestion = 'QUE_DASHBOARD_VIEW'
export const dateOfBirthQuestionCode = 'QUE_DATE_OF_BIRTH'
export const journalDateQuestionCode = 'QUE_JOURNAL_DATE'
export const eligibleAge = 18
export const processView = 'Process View'
export const mentees = 'Mentees'
export const mentors = 'Mentors'
export const agents = 'Agents'
