import {
  faAddressBook,
  faBell,
  faBuilding,
  faCalendar,
  faCalendarCheck,
  faCheckCircle,
  faCity,
  faColumns,
  faComment,
  faEnvelope,
  faFile,
  faFolderOpen,
  faGraduationCap,
  faLaptop,
  faLaptopCode,
  faPaperclip,
  faPeopleArrows,
  faPlus,
  faRobot,
  faRocket,
  faSatellite,
  faSearch,
  faThLarge,
  faUser,
  faUserFriends,
  faUsers,
} from '@fortawesome/free-solid-svg-icons'

const icons = {
  QUE_DRAFTS_GRP: faBell,
  QUE_QUICK_ADD_ITEMS_GRP: faRocket,
  QUE_ADD_ITEMS_GRP: faPlus,
  QUE_DASHBOARD_VIEW: faThLarge,
  QUE_TAB_BUCKET_VIEW: faColumns,
  QUE_TREE_ITEM_CONTACTS_GRP: faUserFriends,
  QUE_TREE_ITEM_INTERNSHIPS: faAddressBook,
  QUE_TREE_ITEM_HOST_COMPANIES: faCity,
  QUE_TREE_ITEM_EDU_PROVIDERS: faGraduationCap,
  QUE_TREE_ITEM_HCRS: faPeopleArrows,
  QUE_TREE_ITEM_APPLICATIONS_APPLIED: faPaperclip,
  QUE_HOST_COMPANY_VIEW: faBuilding,
  QUE_TREE_ITEM_EPRS: faPeopleArrows,
  QUE_TREE_ITEM_INTERNS: faGraduationCap,
  QUE_TREE_ITEM_COMMUNICATIONS: faSatellite,
  QUE_TREE_ITEM_APPOINTMENTS: faCalendar,
  QUE_TREE_ITEM_DOCUMENTS_GRP: faFile,
  QUE_TREE_ITEM_DEV_UI: faRobot,
  // Lojing Temporary Icons
  QUE_TREE_ITEM_PROPERTIES: faBuilding,
  QUE_TABLE_APPLICATIONS: faCheckCircle,
  QUE_TABLE_PROPERTIES: faSearch,

  QUE_PROCESS: faColumns,
  QUE_DASHBOARD: faThLarge,
  QUE_PROFILE: faUser,
  QUE_MESSAGE: faComment,
  QUE_TABLE_HOST_COMPANIES: faCity,
  QUE_TABLE_MESSAGE: faEnvelope,
  QUE_TABLE_EDU_PROVIDERS: faBuilding,
  QUE_TABLE_APPOINTMENTS: faCalendarCheck,
  QUE_TABLE_INTERNSHIPS: faLaptop,
  QUE_TABLE_COMMUNICATIONS: faColumns,
  QUE_TABLE_DOCUMENTS: faFolderOpen,
  QUE_TABLE_DEV_UI: faLaptopCode,

  QUE_CONTACTS: faUsers,

  QUE_DASHBOARD_IM: 'Category',
  QUE_PROCESS_IM: 'Chart',
  QUE_PROFILE_IM: 'User',
  QUE_TAB_BUCKET_VIEW_IM: 'Chart',
  QUE_CONTACTS_IM: 'People',
  QUE_MESSAGE_IM: 'Message',
  QUE_TABLE_MESSAGE_IM: 'Document',
  QUE_TABLE_INTERNSHIPS_IM: 'Work',
  QUE_DOCUMENTS_IM: 'Folder',
  QUE_TABLE_EDU_PROVIDERS_IM: 'Paper',
  QUE_TABLE_HOST_COMPANIES_IM: 'Paper',
  QUE_TABLE_APPOINTMENTS_IM: 'TickSquare',
  QUE_TABLE_COMMUNICATIONS_IM: 'MoreSquare',
  QUE_TABLE_DOCUMENTS_IM: 'Paper',
  QUE_TABLE_DEV_UI_IM: 'Activity',
}

export default icons
