const labels = {
  QUE_DEV_PORTAL_ACCESS: 'DEV PORTAL',
  QUE_QUICK_ADD_ITEMS_GRP: 'Quick Add',
  QUE_ADD_ITEMS_GRP: 'Add',
  QUE_DASHBOARD_VIEW: 'Dashboard',
  QUE_TAB_BUCKET_VIEW: 'Process',
  QUE_TREE_ITEM_CONTACTS_GRP: 'Contacts',
  QUE_TREE_ITEM_INTERNSHIPS: 'Internships',
  QUE_TREE_ITEM_HOST_COMPANIES: 'Companies',
  QUE_TREE_ITEM_EDU_PROVIDERS: 'Edu Providers',
  QUE_TREE_ITEM_HCRS: 'Company Reps',
  QUE_TREE_ITEM_APPLICATIONS_APPLIED: 'Applications',
  QUE_HOST_COMPANY_VIEW: 'Company',
  QUE_TREE_ITEM_EPRS: 'Edu Reps',
  QUE_TREE_ITEM_INTERNS: 'Interns',
  QUE_QA_HOST_CPY_MENU: 'Host Company',
  QUE_QA_HOST_CPY_REP_MENU: 'Host Cpy Rep',
  QUE_QA_EDU_PRO_MENU: 'Edu Provider',
  QUE_QA_EDU_PRO_REP_MENU: 'Edu Pro Rep',
  QUE_QA_INTERNSHIP_MENU: 'Internship',
  QUE_QA_INTERN_MENU: 'Intern',
  QUE_QA_AGENCY_MENU: 'Agency',
  QUE_QA_AGENT_MENU: 'Agent',
  QUE_QA_PERSON_MENU: 'Person',
  QUE_HOST_CPY_MENU: 'Host Company',
  QUE_HOST_CPY_REP_MENU: 'Host Cpy Rep',
  QUE_EDU_PRO_MENU: 'Edu Provider',
  QUE_EDU_PRO_REP_MENU: 'Edu Pro Rep',
  QUE_INTERNSHIP_MENU: 'Internship',
  QUE_INTERN_MENU: 'Intern',
  QUE_AGENCY_MENU: 'Agency',
  QUE_AGENT_MENU: 'Agent',
  QUE_PERSON_MENU: 'Person',
  QUE_DRAFTS_GRP: 'Notifications',
}

export default labels
