import { append, forEach, keys, sort } from 'ramda'
import sortPriLocs from 'app/PCM/helpers/sort-pri-locs'

/**
 * `spillLocs` - A mapped PCM object defined like `{PRI_LOC1:PCM_SIDEBAR,...}` <br/>
 * `fn` - A function that takes a paramter `spillLocs[x]` and returns a JSX element. <br/>
 *  Returns an array of JSX elements generated by `fn`
 */
const mapSpillLocs = (fn: (loc: string) => JSX.Element) => (spillLocs: { [x: string]: string }) => {
  let out: JSX.Element[] = []

  forEach(
    (x: string) => {
      if (fn(spillLocs[x])) {
        out = append(fn(spillLocs[x])!, out)
      }
    },
    sort((a: string, b: string) => sortPriLocs(a)(b), keys(spillLocs) as string[]),
  )

  return out
}

export default mapSpillLocs
